version: '3'

services:
  mongo_service:
    container_name: mongo_container
    image: mongo:jammy
    restart: always
    volumes:
      - mongo_volume:/data/db
  
  mfn_server_service:
    build: .
    container_name: mfn_server_container
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - CLIENT_BASE=

      - COOKIE_ACCESS_1=
      - COOKIE_ACCESS_2=
      - SESSION_SECRET=

      - MONGO_URL=mongodb://mongo_service:27017/mfn

      - AUTH_FACEBOOK_CLIENT_ID=
      - AUTH_FACEBOOK_CLIENT_SECRET=
      - AUTH_FACEBOOK_CALLBACK_URL=http://localhost:${PORT}/auth/facebook/callback

      - AUTH_TWITTER_CONSUMER_KEY=
      - AUTH_TWITTER_CONSUMER_SECRET=
      - AUTH_TWITTER_CALLBACK_URL=http://localhost:${PORT}/auth/twitter/callback

      - AUTH_GOOGLE_CLIENT_ID=
      - AUTH_GOOGLE_CLIENT_SECRET=
      - AUTH_GOOGLE_CALLBACK_URL=http://localhost:${PORT}/auth/google/callback

volumes:
  mongo_volume: {}